create sequence core_tag_id_seq;
SELECT setval('core_tag_id_seq', (SELECT MAX(id) FROM core_tag)+1);

ALTER TABLE "core_tag"
ALTER "id" TYPE integer,
ALTER "id" SET DEFAULT nextval('public.core_tag_id_seq'),
ALTER "id" SET NOT NULL;

INSERT INTO core_tag (id, name) VALUES (317, 'Old tags');

UPDATE core_tag SET parent_tag_id = 317 WHERE id != 317;

INSERT INTO core_tag (name) VALUES ('Methodologies');
INSERT INTO core_tag (name) VALUES ('Geographical areas');
INSERT INTO core_tag (name) VALUES ('Scales');
INSERT INTO core_tag (name) VALUES ('Time horizons');
INSERT INTO core_tag (name) VALUES ('Industrial ecology concepts');
INSERT INTO core_tag (name) VALUES ('Sectors');
INSERT INTO core_tag (name) VALUES ('Indicators');
INSERT INTO core_tag (name) VALUES ('System types');

-- time horizon
UPDATE core_tag SET parent_tag_id = 322 WHERE id IN (78, 186, 79);
UPDATE core_tag SET name = 'Historical time series' WHERE id = 79;

UPDATE core_reference_tags SET tag_id = 79 WHERE tag_id = 80 AND NOT EXISTS (SELECT * FROM core_reference_tags c WHERE c.reference_id = core_reference_tags.reference_id AND tag_id = 79);
DELETE FROM core_reference_tags WHERE tag_id = 80;
DELETE FROM core_tag WHERE id = 80;

-- scale
UPDATE core_tag SET parent_tag_id = 321 WHERE id IN (10,164,30);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Regional', 321);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Sub-national', 321);

-- system type
UPDATE core_tag SET parent_tag_id = 326 WHERE id IN (219,11,67,316);

-- IE concepts
UPDATE core_tag SET parent_tag_id = 323 WHERE id IN (130,281,109,185,259,246,242,87);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Rebound effect', 323);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Degrowth', 323);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Environmental justice', 323);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Sustainable production and consumption', 323);

-- Sectors
UPDATE core_tag SET parent_tag_id = 324 WHERE id IN (237);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Food and agriculture', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Energy', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Tourism', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Packaging', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Construction', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Mining', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Health', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Water', 324);
INSERT INTO core_tag (name, parent_tag_id) VALUES ('Textiles', 324);

--  Indicators
UPDATE core_tag SET parent_tag_id = 325 WHERE id IN (72, 74, 178, 229, 34, 88);

--  Methodologies
UPDATE core_tag SET parent_tag_id = 319 WHERE id IN (85, 289, 54, 299, 65, 240, 135, 86);

--  Geographical areas

INSERT INTO core_tag (id, name, parent_tag_id) VALUES (342, 'Africa', 320);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (343, 'Northern Africa', 342);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (344, 'Algeria', 343);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (345, 'Egypt', 343);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (346, 'Libya', 343);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (347, 'Morocco', 343);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (348, 'Sudan', 343);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (349, 'Tunisia', 343);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (350, 'Western Sahara', 343);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (351, 'Sub-Saharan Africa', 342);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (352, 'Eastern Africa', 351);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (353, 'British Indian Ocean Territory', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (354, 'Burundi', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (355, 'Comoros', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (356, 'Djibouti', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (357, 'Eritrea', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (358, 'Ethiopia', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (359, 'French Southern Territories', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (360, 'Kenya', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (361, 'Madagascar', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (362, 'Malawi', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (363, 'Mauritius', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (364, 'Mayotte', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (365, 'Mozambique', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (366, 'Réunion', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (367, 'Rwanda', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (368, 'Seychelles', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (369, 'Somalia', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (370, 'South Sudan', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (371, 'Uganda', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (372, 'United Republic of Tanzania', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (373, 'Zambia', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (374, 'Zimbabwe', 352);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (375, 'Middle Africa', 351);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (376, 'Angola', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (377, 'Cameroon', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (378, 'Central African Republic', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (379, 'Chad', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (380, 'Congo', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (381, 'Democratic Republic of the Congo', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (382, 'Equatorial Guinea', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (383, 'Gabon', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (384, 'Sao Tome and Principe', 375);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (385, 'Southern Africa', 351);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (386, 'Botswana', 385);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (387, 'Eswatini', 385);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (388, 'Lesotho', 385);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (389, 'Namibia', 385);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (390, 'South Africa', 385);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (391, 'Western Africa', 351);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (392, 'Benin', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (393, 'Burkina Faso', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (394, 'Cabo Verde', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (395, 'Côte d’Ivoire', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (396, 'Gambia', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (397, 'Ghana', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (398, 'Guinea', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (399, 'Guinea-Bissau', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (400, 'Liberia', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (401, 'Mali', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (402, 'Mauritania', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (403, 'Niger', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (404, 'Nigeria', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (405, 'Saint Helena', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (406, 'Senegal', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (407, 'Sierra Leone', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (408, 'Togo', 391);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (409, 'Americas', 320);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (410, 'Latin America and the Caribbean', 409);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (411, 'Caribbean', 410);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (412, 'Anguilla', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (413, 'Antigua and Barbuda', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (414, 'Aruba', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (415, 'Bahamas', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (416, 'Barbados', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (417, 'Bonaire, Sint Eustatius and Saba', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (418, 'British Virgin Islands', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (419, 'Cayman Islands', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (420, 'Cuba', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (421, 'Curaçao', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (422, 'Dominica', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (423, 'Dominican Republic', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (424, 'Grenada', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (425, 'Guadeloupe', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (426, 'Haiti', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (427, 'Jamaica', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (428, 'Martinique', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (429, 'Montserrat', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (430, 'Puerto Rico', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (431, 'Saint Barthélemy', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (432, 'Saint Kitts and Nevis', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (433, 'Saint Lucia', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (434, 'Saint Martin (French Part)', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (435, 'Saint Vincent and the Grenadines', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (436, 'Sint Maarten (Dutch part)', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (437, 'Trinidad and Tobago', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (438, 'Turks and Caicos Islands', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (439, 'United States Virgin Islands', 411);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (440, 'Central America', 410);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (441, 'Belize', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (442, 'Costa Rica', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (443, 'El Salvador', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (444, 'Guatemala', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (445, 'Honduras', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (446, 'Mexico', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (447, 'Nicaragua', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (448, 'Panama', 440);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (449, 'South America', 410);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (450, 'Argentina', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (451, 'Bolivia (Plurinational State of)', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (452, 'Bouvet Island', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (453, 'Brazil', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (454, 'Chile', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (455, 'Colombia', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (456, 'Ecuador', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (457, 'Falkland Islands (Malvinas)', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (458, 'French Guiana', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (459, 'Guyana', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (460, 'Paraguay', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (461, 'Peru', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (462, 'South Georgia and the South Sandwich Islands', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (463, 'Suriname', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (464, 'Uruguay', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (465, 'Venezuela (Bolivarian Republic of)', 449);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (466, 'Northern America', 409);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (467, 'Bermuda', 466);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (468, 'Canada', 466);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (469, 'Greenland', 466);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (470, 'Saint Pierre and Miquelon', 466);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (471, 'United States of America', 466);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (472, 'Asia', 320);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (473, 'Central Asia', 472);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (474, 'Kazakhstan', 473);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (475, 'Kyrgyzstan', 473);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (476, 'Tajikistan', 473);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (477, 'Turkmenistan', 473);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (478, 'Uzbekistan', 473);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (479, 'Eastern Asia', 472);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (480, 'China', 479);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (481, 'China, Hong Kong Special Administrative Region', 479);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (482, 'China, Macao Special Administrative Region', 479);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (483, 'Democratic People''s Republic of Korea', 479);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (484, 'Japan', 479);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (485, 'Mongolia', 479);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (486, 'Republic of Korea', 479);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (487, 'South-eastern Asia', 472);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (488, 'Brunei Darussalam', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (489, 'Cambodia', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (490, 'Indonesia', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (491, 'Lao People''s Democratic Republic', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (492, 'Malaysia', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (493, 'Myanmar', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (494, 'Philippines', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (495, 'Singapore', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (496, 'Thailand', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (497, 'Timor-Leste', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (498, 'Viet Nam', 487);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (499, 'Southern Asia', 472);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (500, 'Afghanistan', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (501, 'Bangladesh', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (502, 'Bhutan', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (503, 'India', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (504, 'Iran (Islamic Republic of)', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (505, 'Maldives', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (506, 'Nepal', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (507, 'Pakistan', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (508, 'Sri Lanka', 499);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (509, 'Western Asia', 472);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (510, 'Armenia', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (511, 'Azerbaijan', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (512, 'Bahrain', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (513, 'Cyprus', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (514, 'Georgia', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (515, 'Iraq', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (516, 'Israel', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (517, 'Jordan', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (518, 'Kuwait', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (519, 'Lebanon', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (520, 'Oman', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (521, 'Qatar', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (522, 'Saudi Arabia', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (523, 'State of Palestine', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (524, 'Syrian Arab Republic', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (525, 'Turkey', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (526, 'United Arab Emirates', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (527, 'Yemen', 509);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (528, 'Europe', 320);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (529, 'Eastern Europe', 528);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (530, 'Belarus', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (531, 'Bulgaria', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (532, 'Czechia', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (533, 'Hungary', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (534, 'Poland', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (535, 'Republic of Moldova', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (536, 'Romania', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (537, 'Russian Federation', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (538, 'Slovakia', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (539, 'Ukraine', 529);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (540, 'Northern Europe', 528);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (541, 'Åland Islands', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (542, 'Channel Islands', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (543, 'Guernsey', 542);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (544, 'Jersey', 542);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (545, 'Sark', 542);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (546, 'Denmark', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (547, 'Estonia', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (548, 'Faroe Islands', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (549, 'Finland', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (550, 'Iceland', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (551, 'Ireland', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (552, 'Isle of Man', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (553, 'Latvia', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (554, 'Lithuania', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (555, 'Norway', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (556, 'Svalbard and Jan Mayen Islands', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (557, 'Sweden', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (558, 'United Kingdom of Great Britain and Northern Ireland', 540);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (559, 'Southern Europe', 528);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (560, 'Albania', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (561, 'Andorra', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (562, 'Bosnia and Herzegovina', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (563, 'Croatia', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (564, 'Gibraltar', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (565, 'Greece', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (566, 'Holy See', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (567, 'Italy', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (568, 'Malta', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (569, 'Montenegro', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (570, 'Portugal', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (571, 'San Marino', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (572, 'Serbia', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (573, 'Slovenia', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (574, 'Spain', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (575, 'The former Yugoslav Republic of Macedonia', 559);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (576, 'Western Europe', 528);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (577, 'Austria', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (578, 'Belgium', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (579, 'France', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (580, 'Germany', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (581, 'Liechtenstein', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (582, 'Luxembourg', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (583, 'Monaco', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (584, 'Netherlands', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (585, 'Switzerland', 576);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (586, 'Oceania', 320);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (587, 'Australia and New Zealand', 586);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (588, 'Australia', 587);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (589, 'Christmas Island', 587);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (590, 'Cocos (Keeling) Islands', 587);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (591, 'Heard Island and McDonald Islands', 587);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (592, 'New Zealand', 587);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (593, 'Norfolk Island', 587);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (594, 'Melanesia', 586);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (595, 'Fiji', 594);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (596, 'New Caledonia', 594);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (597, 'Papua New Guinea', 594);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (598, 'Solomon Islands', 594);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (599, 'Vanuatu', 594);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (600, 'Micronesia', 586);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (601, 'Guam', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (602, 'Kiribati', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (603, 'Marshall Islands', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (604, 'Micronesia (Federated States of)', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (605, 'Nauru', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (606, 'Northern Mariana Islands', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (607, 'Palau', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (608, 'United States Minor Outlying Islands', 600);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (609, 'Polynesia', 586);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (610, 'American Samoa', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (611, 'Cook Islands', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (612, 'French Polynesia', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (613, 'Niue', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (614, 'Pitcairn', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (615, 'Samoa', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (616, 'Tokelau', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (617, 'Tonga', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (618, 'Tuvalu', 609);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (619, 'Wallis and Futuna Islands', 609);

INSERT INTO core_tag (id, name, parent_tag_id, description) VALUES (620, 'By region', 320, 'These regions are based on the United Nations Statistics Division''s methodology, available at  https://unstats.un.org/unsd/methodology/m49/overview/ (retrieved November 2, 2018)');
UPDATE core_tag SET parent_tag_id = 620 WHERE parent_tag_id = 320 AND id NOT IN (620);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (621, 'By economic zone', 320);
INSERT INTO core_tag (id, name, parent_tag_id) VALUES (622, 'European Union', 621);

UPDATE core_reference_tags SET tag_id = 274 WHERE tag_id = 300 AND NOT EXISTS (SELECT * FROM core_reference_tags c WHERE c.reference_id = core_reference_tags.reference_id AND tag_id = 274);
DELETE FROM core_reference_tags WHERE tag_id = 300;
DELETE FROM core_tag WHERE id = 300;
DELETE FROM core_tag WHERE id = 279;

UPDATE core_reference_tags SET tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Poland') WHERE tag_id = 227;
DELETE FROM core_tag WHERE id = 227;

UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Ghana') WHERE id = 256;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Australia') WHERE id = 244;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Jordan') WHERE id = 125;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Netherlands') WHERE id = 220;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Greece') WHERE id = 208;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 198;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Bangladesh') WHERE id = 137;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Thailand') WHERE id = 138;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Spain') WHERE id = 190;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 95;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Germany') WHERE id = 265;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United Kingdom of Great Britain and Northern Ireland') WHERE id = 273;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Colombia') WHERE id = 121;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Australia') WHERE id = 245;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'France') WHERE id = 263;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Belgium') WHERE id = 180;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 280;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Hungary') WHERE id = 266;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Argentina') WHERE id = 102;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Egypt') WHERE id = 154;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Canada') WHERE id = 189;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'South Africa') WHERE id = 108;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Venezuela (Bolivarian Republic of)') WHERE id = 311;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Belgium') WHERE id = 171;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 283;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 215;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Sri Lanka') WHERE id = 193;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Brazil') WHERE id = 222;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Senegal') WHERE id = 230;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'India') WHERE id = 62;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United Kingdom of Great Britain and Northern Ireland') WHERE id = 199;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Bangladesh') WHERE id = 152;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Italy') WHERE id = 225;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Germany') WHERE id = 210;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Switzerland') WHERE id = 194;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Egypt') WHERE id = 166;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United Kingdom of Great Britain and Northern Ireland') WHERE id = 197;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Poland') WHERE id = 226;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Sweden') WHERE id = 45;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 143;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Germany') WHERE id = 111;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 286;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Finland') WHERE id = 224;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Viet Nam') WHERE id = 170;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China, Hong Kong Special Administrative Region') WHERE id = 98;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'France') WHERE id = 250;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 260;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Turkey') WHERE id = 149;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Indonesia') WHERE id = 148;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Pakistan') WHERE id = 153;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Nepal') WHERE id = 204;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Japan') WHERE id = 258;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Morocco') WHERE id = 172;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Japan') WHERE id = 274;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'India') WHERE id = 155;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Nigeria') WHERE id = 151;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'France') WHERE id = 253;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Peru') WHERE id = 310;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Ireland') WHERE id = 270;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Sweden') WHERE id = 92;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Portugal') WHERE id = 20;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United Kingdom of Great Britain and Northern Ireland') WHERE id = 120;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Slovenia') WHERE id = 207;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United Kingdom of Great Britain and Northern Ireland') WHERE id = 146;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 139;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China, Macao Special Administrative Region') WHERE id = 140;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Spain') WHERE id = 191;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Argentina') WHERE id = 312;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Sweden') WHERE id = 238;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Philippines') WHERE id = 127;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'France') WHERE id = 254;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Australia') WHERE id = 184;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Mexico') WHERE id = 99;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 173;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Italy') WHERE id = 261;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Argentina') WHERE id = 305;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Uruguay') WHERE id = 308;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Russian Federation') WHERE id = 142;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'India') WHERE id = 156;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Italy') WHERE id = 202;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 297;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 61;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 134;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 64;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Sweden') WHERE id = 179;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Japan') WHERE id = 144;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Norway') WHERE id = 49;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'France') WHERE id = 9;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Australia') WHERE id = 243;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 278;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 200;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Portugal') WHERE id = 205;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Czechia') WHERE id = 212;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Canada') WHERE id = 257;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Ecuador') WHERE id = 309;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'France') WHERE id = 252;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Iceland') WHERE id = 267;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Brazil') WHERE id = 101;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Netherlands') WHERE id = 195;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 284;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Chile') WHERE id = 262;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Brazil') WHERE id = 100;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 201;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Republic of Korea') WHERE id = 123;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 122;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 239;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 150;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Singapore') WHERE id = 112;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'South Africa') WHERE id = 268;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Sweden') WHERE id = 113;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Germany') WHERE id = 211;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 23;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Australia') WHERE id = 187;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United States of America') WHERE id = 275;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 41;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Argentina') WHERE id = 304;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Iran (Islamic Republic of)') WHERE id = 145;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 133;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Japan') WHERE id = 141;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Canada') WHERE id = 115;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Canada') WHERE id = 188;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'Austria') WHERE id = 104;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'United Kingdom of Great Britain and Northern Ireland') WHERE id = 103;
UPDATE core_tag SET parent_tag_id = (SELECT id FROM core_tag WHERE id >= 342 AND name = 'China') WHERE id = 216;

UPDATE core_tag SET hidden = TRUE WHERE parent_tag_id = 317 OR id = 317;

ALTER TABLE "core_tag"
ALTER "id" TYPE integer,
ALTER "id" SET DEFAULT nextval('public.core_tag_id_seq'),
ALTER "id" SET NOT NULL;
