# Generated by Django 2.1.2 on 2018-10-28 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staf', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiplicity', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='materials',
            field=models.ManyToManyField(blank=True, to='staf.Material'),
        ),
        migrations.AddField(
            model_name='topic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='multiplicity.Topic'),
        ),
        migrations.AddField(
            model_name='referencespacetypedescription',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='referencespacetypedescription',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpaceType'),
        ),
        migrations.AddField(
            model_name='referencespacetype',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.Topic'),
        ),
        migrations.AddField(
            model_name='referencespacelocation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='referencespacefeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.Feature'),
        ),
        migrations.AddField(
            model_name='referencespacefeature',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='referencespacecsv',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='referencespacecsv',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpaceType'),
        ),
        migrations.AddField(
            model_name='referencespacecsv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referencespace',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_location', to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='referencespace',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_location', to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='referencespace',
            name='csv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpaceCSV'),
        ),
        migrations.AddField(
            model_name='referencespace',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multiplicity.ReferenceSpaceLocation'),
        ),
        migrations.AddField(
            model_name='referencespace',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpaceType'),
        ),
        migrations.AddField(
            model_name='information',
            name='references',
            field=models.ManyToManyField(blank=True, to='core.Reference'),
        ),
        migrations.AddField(
            model_name='information',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='information',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.Topic'),
        ),
        migrations.AddField(
            model_name='information',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpaceType'),
        ),
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpaceType'),
        ),
        migrations.AddField(
            model_name='feature',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.Unit'),
        ),
        migrations.AddField(
            model_name='dqirating',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.DQI'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='destination_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationdataset', to='staf.Process'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='destination_reference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinationreferencetype', to='multiplicity.ReferenceSpaceType'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='origin_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origindataset', to='staf.Process'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='origin_reference_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originreferencetype', to='multiplicity.ReferenceSpaceType'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='standard_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.Material'),
        ),
        migrations.AddField(
            model_name='datasettype',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.Topic'),
        ),
    ]
