# Generated by Django 2.1.2 on 2018-10-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0002_auto_20181028_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='graphtype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='graphtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='graphtype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='graphtype',
            name='slug',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
