# Generated by Django 2.1.2 on 2018-10-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0002_remove_dataset_graph'),
        ('multiplicity', '0003_auto_20181028_1539'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphType',
        ),
    ]
