# Generated by Django 2.1.2 on 2018-10-28 15:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0004_delete_graphtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Content')),
            ],
        ),
    ]
