# Generated by Django 2.1.3 on 2018-11-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0006_auto_20181119_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.DatasetTypeStructure'),
        ),
    ]
