# Generated by Django 2.1.3 on 2018-11-23 06:50

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0010_photo_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='space',
            new_name='primary_space',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=stdimage.models.StdImageField(default=1, upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='topic',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.Topic'),
        ),
    ]
