# Generated by Django 2.1.3 on 2018-11-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0011_auto_20181123_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasettype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
