# Generated by Django 2.1.3 on 2018-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0015_auto_20181125_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='dataset_types',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='multiplicity.DatasetType'),
        ),
    ]
