# Generated by Django 2.1.3 on 2018-11-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0007_process_code'),
        ('multiplicity', '0016_auto_20181125_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='processes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_separator': False}, to='staf.Process'),
        ),
    ]
