# Generated by Django 2.1.3 on 2018-12-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0020_processgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='processgroup',
            field=models.ManyToManyField(blank=True, to='multiplicity.ProcessGroup'),
        ),
    ]
