# Generated by Django 2.1.3 on 2018-12-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0021_information_processgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='processes',
            field=models.ManyToManyField(blank=True, to='staf.Process'),
        ),
    ]
