# Generated by Django 2.1.3 on 2018-12-08 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0009_dataset_process'),
        ('multiplicity', '0022_auto_20181208_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespacetype',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.Process'),
        ),
    ]
