# Generated by Django 2.1.3 on 2018-12-08 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0010_process_slug'),
        ('multiplicity', '0023_referencespacetype_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='topic',
        ),
        migrations.AddField(
            model_name='photo',
            name='process',
            field=models.ForeignKey(blank=True, limit_choices_to={'slug__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.Process'),
        ),
    ]
