# Generated by Django 2.1.3 on 2018-12-08 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0011_auto_20181208_0714'),
        ('multiplicity', '0024_auto_20181208_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='processes',
        ),
        migrations.RemoveField(
            model_name='information',
            name='processgroup',
        ),
        migrations.RemoveField(
            model_name='information',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='information',
            name='type',
        ),
        migrations.AddField(
            model_name='information',
            name='process',
            field=models.ForeignKey(blank=True, limit_choices_to={'slug__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.Process'),
        ),
    ]
