# Generated by Django 2.1.3 on 2018-12-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0025_auto_20181208_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencespacetype',
            name='process',
            field=models.ForeignKey(blank=True, limit_choices_to={'slug__isnull': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='staf.Process'),
        ),
    ]
