# Generated by Django 2.1.3 on 2018-12-11 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0027_auto_20181208_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.Photo'),
        ),
    ]
