# Generated by Django 2.1.3 on 2018-12-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0031_referencetypephoto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferenceTypePhoto',
            new_name='ReferencePhoto',
        ),
    ]
