# Generated by Django 2.1.3 on 2019-01-19 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0032_auto_20181219_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='secondary_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='multiplicity.ReferenceSpace'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='primary_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_gallery', to='multiplicity.ReferenceSpace'),
        ),
    ]
