# Generated by Django 2.1.3 on 2019-01-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0033_auto_20190119_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespace',
            name='image',
        ),
    ]
