# Generated by Django 2.1.3 on 2019-01-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0034_remove_referencespace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='exclusively_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
    ]
