# Generated by Django 2.1.3 on 2019-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0036_information_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencespacelocation',
            options={'ordering': ['-timeframe']},
        ),
        migrations.AddField(
            model_name='referencespacelocation',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
