# Generated by Django 2.1.3 on 2019-01-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0037_auto_20190127_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpaceType')),
            ],
        ),
    ]
