# Generated by Django 2.1.3 on 2019-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0038_mtu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('map', 'Map')], default='photo', max_length=6),
        ),
    ]
