# Generated by Django 2.1.3 on 2019-01-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0039_auto_20190129_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='type',
            field=models.CharField(choices=[('photo', 'Photo'), ('map', 'Map')], default='photo', max_length=6),
        ),
    ]
