# Generated by Django 2.1.3 on 2019-02-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0042_auto_20190209_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencespacesector',
            name='topic',
        ),
        migrations.AddField(
            model_name='referencespacesector',
            name='process_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ProcessGroup'),
            preserve_default=False,
        ),
    ]
