# Generated by Django 2.1.3 on 2019-03-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0044_referencespacelocation_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtu',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='referencespace',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
