# Generated by Django 2.1.3 on 2019-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0045_auto_20190304_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespacelocation',
            name='end',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='referencespacelocation',
            name='start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
