# Generated by Django 2.1.3 on 2019-03-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0046_auto_20190320_0539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencespacelocation',
            options={'ordering': ['-start']},
        ),
        migrations.RemoveField(
            model_name='referencespacelocation',
            name='timeframe',
        ),
    ]
