# Generated by Django 2.1.3 on 2019-04-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0048_photo_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencespace',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='multiplicity.ReferenceSpace'),
        ),
    ]
