# Generated by Django 2.1.3 on 2018-12-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20181213_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskforceticket',
            name='good_entry_task',
            field=models.BooleanField(default=False),
        ),
    ]
