# Generated by Django 2.1.3 on 2019-02-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20181215_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='show_publicly',
            field=models.BooleanField(default=True),
        ),
    ]
