# Generated by Django 2.1.2 on 2018-11-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0003_dataset_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasettimeperiod',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasettimeperiod',
            name='timeframe',
        ),
        migrations.DeleteModel(
            name='DatasetTimePeriod',
        ),
    ]
