# Generated by Django 2.1.3 on 2018-11-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0005_auto_20181123_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='topics',
            field=models.ManyToManyField(blank=True, to='multiplicity.Topic'),
        ),
    ]
