# Generated by Django 2.1.3 on 2018-11-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0006_auto_20181125_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
