# Generated by Django 2.1.3 on 2018-12-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0007_process_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['id']},
        ),
    ]
