# Generated by Django 2.1.3 on 2018-12-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0009_dataset_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
