# Generated by Django 2.1.3 on 2019-03-22 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0011_auto_20181208_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='staf.Dataset'),
        ),
    ]
