# Generated by Django 2.1.3 on 2019-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0012_auto_20190322_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
