# Generated by Django 2.1.2 on 2018-10-28 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('multiplicity', '0002_auto_20181028_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referenceorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='referenceorganization',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reference'),
        ),
        migrations.AddField(
            model_name='reference',
            name='authors',
            field=models.ManyToManyField(to='core.People'),
        ),
        migrations.AddField(
            model_name='reference',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Journal'),
        ),
        migrations.AddField(
            model_name='reference',
            name='organizations',
            field=models.ManyToManyField(through='core.ReferenceOrganization', to='core.Organization'),
        ),
        migrations.AddField(
            model_name='reference',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
        migrations.AddField(
            model_name='reference',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ReferenceType'),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='peopleaffiliation',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='peopleaffiliation',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.People'),
        ),
        migrations.AddField(
            model_name='people',
            name='city',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_city', to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='people',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_country', to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='people',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='multiplicity.ReferenceSpace'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Organization'),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Publisher'),
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, to='core.People'),
        ),
        migrations.AddField(
            model_name='article',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionparent', to='core.Article'),
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='reference',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
    ]
