# Generated by Django 2.1.2 on 2018-10-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.CharField(choices=[('about', 'About'), ('community', 'Community'), ('research', 'Research'), ('resources', 'Resources'), ('cities', 'Cities'), ('whatwedo', 'What We Do'), ('newsevents', 'News and Events')], default='about', max_length=20),
        ),
    ]
