# Generated by Django 2.1.2 on 2018-10-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181029_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='article',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
