# Generated by Django 2.1.2 on 2018-10-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181029_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='people',
            field=models.ManyToManyField(blank=True, null=True, to='core.People'),
        ),
    ]
