# Generated by Django 2.1.2 on 2018-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181030_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deleted', 'Deleted')], db_index=True, max_length=8),
        ),
    ]
