# Generated by Django 2.1.3 on 2018-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20181103_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False),
            preserve_default=False,
        ),
    ]
