# Generated by Django 2.1.2 on 2018-11-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181104_2313'),
        ('core', '0018_auto_20181107_1128'),
    ]

    operations = [
    ]
