# Generated by Django 2.1.2 on 2018-11-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20181125_0510'),
        ('core', '0019_merge_20181118_0704'),
    ]

    operations = [
    ]
