# Generated by Django 2.1.2 on 2018-11-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_merge_20181125_0515'),
        ('core', '0021_auto_20181125_0602'),
    ]

    operations = [
    ]
