# Generated by Django 2.1.3 on 2018-12-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0028_information_photo'),
        ('core', '0023_auto_20181211_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='primary_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
    ]
