# Generated by Django 2.1.3 on 2018-12-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_reference_primary_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='references'),
        ),
    ]
