# Generated by Django 2.1.2 on 2018-12-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_reference_primary_space'),
        ('core', '0022_merge_20181125_0652'),
    ]

    operations = [
    ]
