# Generated by Django 2.1.3 on 2018-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0011_auto_20181208_0714'),
        ('multiplicity', '0028_information_photo'),
        ('core', '0025_reference_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='location',
        ),
        migrations.AddField(
            model_name='organization',
            name='processes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'slug__isnull': False}, to='staf.Process'),
        ),
        migrations.AddField(
            model_name='organization',
            name='reference_spaces',
            field=models.ManyToManyField(blank=True, to='multiplicity.ReferenceSpace'),
        ),
    ]
