# Generated by Django 2.1.2 on 2018-12-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20181211_0624'),
        ('core', '0025_reference_file'),
    ]

    operations = [
    ]
