# Generated by Django 2.1.2 on 2018-12-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20181211_0632'),
        ('core', '0026_auto_20181211_0937'),
    ]

    operations = [
    ]
