# Generated by Django 2.1.2 on 2019-01-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190117_1854'),
        ('core', '0027_merge_20181211_0943'),
    ]

    operations = [
    ]
