# Generated by Django 2.1.3 on 2019-01-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20190117_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='references',
            field=models.ManyToManyField(blank=True, to='core.Reference'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('research', 'Thesis project'), ('regular', 'Research project'), ('applied', 'Applied research')], max_length=20),
        ),
    ]
