# Generated by Django 2.1.2 on 2019-01-18 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_merge_20190117_1907'),
        ('core', '0028_auto_20190118_1624'),
    ]

    operations = [
    ]
