# Generated by Django 2.1.3 on 2019-01-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190118_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='references',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'active'}, to='core.Reference'),
        ),
    ]
