# Generated by Django 2.1.3 on 2019-01-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0033_auto_20190119_0911'),
        ('core', '0029_auto_20190119_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='primary_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.ReferenceSpace'),
        ),
    ]
