# Generated by Django 2.1.3 on 2019-01-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0033_auto_20190119_0911'),
        ('core', '0032_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='multiplicity.License'),
        ),
    ]
