# Generated by Django 2.1.2 on 2019-01-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20190118_1647'),
        ('core', '0032_video_thumbnail'),
    ]

    operations = [
    ]
