# Generated by Django 2.1.2 on 2019-01-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_video_license'),
        ('core', '0033_merge_20190119_1009'),
    ]

    operations = [
    ]
