# Generated by Django 2.1.3 on 2019-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_video_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thesistype',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('masters', 'Masters'), ('phd', 'PhD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('theses', 'Thesis project'), ('projects', 'Research project'), ('applied', 'Applied research')], max_length=20),
        ),
    ]
