# Generated by Django 2.1.3 on 2019-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20190120_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('theses', 'Theses projects'), ('projects', 'Research projects'), ('applied', 'Applied research')], max_length=20),
        ),
    ]
