# Generated by Django 2.1.2 on 2019-01-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20190120_1000'),
        ('core', '0034_merge_20190119_1200'),
    ]

    operations = [
    ]
