# Generated by Django 2.1.3 on 2019-02-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20190203_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['-year', 'title']},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='userlog',
            name='model_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
