# Generated by Django 2.1.2 on 2019-02-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_merge_20190120_1014'),
        ('core', '0037_auto_20190203_1412'),
    ]

    operations = [
    ]
