# Generated by Django 2.1.3 on 2019-02-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0037_auto_20190203_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='people',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('deceased', 'Deceased'), ('inactive', 'Inactive'), ('pending', 'Pending Review')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='peoplenote',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.People'),
        ),
    ]
