# Generated by Django 2.1.3 on 2019-02-05 06:09

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0038_auto_20190205_0545'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='people',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peoplenote',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
