# Generated by Django 2.1.3 on 2019-02-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20190205_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
