# Generated by Django 2.1.2 on 2019-02-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_merge_20190205_0807'),
        ('core', '0040_auto_20190205_0908'),
    ]

    operations = [
    ]
