# Generated by Django 2.1.2 on 2019-02-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_merge_20190205_0911'),
        ('core', '0042_auto_20190205_1553'),
    ]

    operations = [
    ]
