# Generated by Django 2.1.2 on 2019-02-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_merge_20190205_1924'),
        ('core', '0043_auto_20190206_0350'),
    ]

    operations = [
    ]
