# Generated by Django 2.1.3 on 2019-02-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20190208_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parent_tag',
            field=models.ForeignKey(blank=True, limit_choices_to={'hidden': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='core.Tag'),
        ),
    ]
