# Generated by Django 2.1.2 on 2019-02-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20190206_0353'),
        ('core', '0044_auto_20190208_1813'),
    ]

    operations = [
    ]
