# Generated by Django 2.1.3 on 2019-02-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20190210_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'ordering': ['firstname', 'lastname']},
        ),
    ]
