# Generated by Django 2.1.2 on 2019-02-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20190210_1147'),
        ('core', '0045_merge_20190208_1816'),
    ]

    operations = [
    ]
