# Generated by Django 2.1.2 on 2019-02-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20190212_0403'),
        ('core', '0047_merge_20190210_1343'),
    ]

    operations = [
    ]
