# Generated by Django 2.1.3 on 2019-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_videocollection_show_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
