# Generated by Django 2.1.2 on 2019-02-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_merge_20190212_0405'),
        ('core', '0048_videocollection_show_in_list'),
    ]

    operations = [
    ]
