# Generated by Django 2.1.2 on 2019-02-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_merge_20190212_0544'),
        ('core', '0049_article_head'),
    ]

    operations = [
    ]
