# Generated by Django 2.1.3 on 2019-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_article_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='includes_form',
            field=models.BooleanField(default=False),
        ),
    ]
