# Generated by Django 2.1.2 on 2019-02-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_article_includes_form'),
        ('core', '0050_merge_20190212_0720'),
    ]

    operations = [
    ]
