# Generated by Django 2.1.3 on 2019-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_article_includes_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('theses', 'Theses'), ('projects', 'Projects'), ('applied', 'Applied research')], max_length=20),
        ),
    ]
