# Generated by Django 2.1.3 on 2019-02-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20190212_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='estimated_date',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
