# Generated by Django 2.1.2 on 2019-02-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_merge_20190212_0808'),
        ('core', '0051_auto_20190212_1334'),
    ]

    operations = [
    ]
