# Generated by Django 2.1.2 on 2019-02-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_merge_20190212_1336'),
        ('core', '0052_event_estimated_date'),
    ]

    operations = [
    ]
