# Generated by Django 2.1.2 on 2019-03-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20190212_1354'),
        ('core', '0053_auto_20190304_0733'),
    ]

    operations = [
    ]
