# Generated by Django 2.1.2 on 2019-03-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20190305_1613'),
        ('core', '0054_merge_20190304_0758'),
    ]

    operations = [
    ]
