# Generated by Django 2.1.2 on 2019-04-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_merge_20190305_1616'),
        ('core', '0055_auto_20190415_1548'),
    ]

    operations = [
    ]
