# Generated by Django 2.1.3 on 2019-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staf', '0013_csv_active'),
        ('core', '0055_auto_20190415_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='materials',
            field=models.ManyToManyField(blank=True, to='staf.Material'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='primary_space',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
