# Generated by Django 2.1.2 on 2019-04-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20190419_0709'),
        ('core', '0056_merge_20190415_1608'),
    ]

    operations = [
    ]
