# Generated by Django 2.1.3 on 2019-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20190419_0709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocollection',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='videocollection',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
