# Generated by Django 2.1.2 on 2019-04-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20190424_1552'),
        ('core', '0058_merge_20190419_1012'),
    ]

    operations = [
    ]
