# Generated by Django 2.1.3 on 2019-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20190424_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='collection',
        ),
        migrations.AddField(
            model_name='video',
            name='collection',
            field=models.ManyToManyField(blank=True, to='core.VideoCollection'),
        ),
    ]
