# Generated by Django 2.1.2 on 2019-04-25 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20190425_0755'),
        ('core', '0059_merge_20190424_1557'),
    ]

    operations = [
    ]
