# Generated by Django 2.1.2 on 2019-04-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20190425_0804'),
        ('core', '0060_merge_20190425_0803'),
    ]

    operations = [
    ]
