# Generated by Django 2.2.2 on 2019-06-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20190425_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='isbn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
