# Generated by Django 2.2.2 on 2019-06-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_reference_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
