# Generated by Django 2.1.2 on 2019-06-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_merge_20190425_0814'),
        ('core', '0062_reference_comments'),
    ]

    operations = [
    ]
