# Generated by Django 2.2.2 on 2019-07-01 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_reference_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='journal',
            field=models.ForeignKey(blank=True, help_text='If the journal does not appear in the list, please leave empty and add the name in the comments', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Journal'),
        ),
    ]
