# Generated by Django 2.2.2 on 2019-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20190701_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='journals'),
        ),
        migrations.AddField(
            model_name='organization',
            name='researchgate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
