# Generated by Django 2.1.2 on 2019-07-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_merge_20190618_1508'),
        ('core', '0063_auto_20190701_0634'),
    ]

    operations = [
    ]
