# Generated by Django 2.1.2 on 2019-07-31 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20190731_0957'),
        ('core', '0064_merge_20190704_0923'),
    ]

    operations = [
    ]
