# Generated by Django 2.2.2 on 2019-08-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20190802_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('funder', 'Funder'), ('commissioner', 'Commissioner'), ('organization', 'Organization')], max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(through='core.ProjectOrganization', to='core.Organization'),
        ),
    ]
