# Generated by Django 2.1.2 on 2019-08-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20190802_1323'),
        ('core', '0068_merge_20190731_1000'),
    ]

    operations = [
    ]
