# Generated by Django 2.2.2 on 2019-08-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20190802_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleaffiliation',
            name='start',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
