# Generated by Django 2.1.2 on 2019-08-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_merge_20190802_1326'),
        ('core', '0070_auto_20190802_1331'),
    ]

    operations = [
    ]
