# Generated by Django 2.2.2 on 2019-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20190802_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='core.Organization'),
        ),
        migrations.DeleteModel(
            name='PeopleAffiliation',
        ),
    ]
