# Generated by Django 2.1.2 on 2019-08-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20190802_1405'),
        ('core', '0071_merge_20190802_1332'),
    ]

    operations = [
    ]
