# Generated by Django 2.2.2 on 2019-08-02 14:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_dataviz_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataviz',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
