# Generated by Django 2.2.2 on 2019-08-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20190802_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='image',
            field=models.ImageField(default='test', upload_to='dataviz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='source',
            field=models.CharField(blank=True, help_text='Name of the source website/article -- ONLY enter if this is not linked to a publication', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='url',
            field=models.CharField(blank=True, help_text='URL of the source website/article -- ONLY enter if this is not linked to a publication', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataviz',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year of the data being visualized -- ONLY enter if this is not linked to a publication', null=True),
        ),
    ]
