# Generated by Django 2.2.2 on 2019-08-02 15:12

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20190802_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataviz',
            name='image',
            field=stdimage.models.StdImageField(upload_to='dataviz'),
        ),
    ]
