# Generated by Django 2.1.2 on 2019-08-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20190802_1420'),
        ('core', '0072_merge_20190802_1405'),
    ]

    operations = [
    ]
