# Generated by Django 2.1.2 on 2019-08-05 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_merge_20190802_1454'),
        ('core', '0076_auto_20190802_1512'),
    ]

    operations = [
    ]
