# Generated by Django 2.2.2 on 2019-08-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20190802_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('academic', 'Research Institution'), ('universities', 'Universities'), ('city_government', 'City Government'), ('regional_government', 'Regional Government'), ('national_government', 'National Government'), ('statistical_agency', 'Statistical Agency'), ('private_sector', 'Private Sector'), ('publisher', 'Publishers'), ('ngo', 'NGO'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(blank=True, through='core.ProjectOrganization', to='core.Organization'),
        ),
    ]
