# Generated by Django 2.1.2 on 2019-08-06 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_merge_20190805_1519'),
        ('core', '0077_auto_20190806_1324'),
    ]

    operations = [
    ]
