# Generated by Django 2.2.2 on 2019-08-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20190806_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(blank=True, help_text='Square photos are best - please resize to 350x350 pixels', null=True, upload_to='people'),
        ),
    ]
