# Generated by Django 2.1.2 on 2019-08-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20190807_0534'),
        ('core', '0078_merge_20190806_1324'),
    ]

    operations = [
    ]
