# Generated by Django 2.1.2 on 2019-08-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_auto_20190807_1602'),
        ('core', '0079_merge_20190807_0534'),
    ]

    operations = [
    ]
