# Generated by Django 2.2.2 on 2019-08-13 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0050_auto_20190701_0635'),
        ('core', '0080_auto_20190813_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasets', models.BooleanField()),
                ('news', models.BooleanField()),
                ('events', models.BooleanField()),
                ('publications', models.BooleanField()),
                ('dataviz', models.BooleanField()),
                ('multimedia', models.BooleanField()),
                ('projects', models.BooleanField()),
                ('theses', models.BooleanField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.People')),
                ('reference_spaces', models.ManyToManyField(blank=True, to='multiplicity.ReferenceSpace')),
            ],
        ),
    ]
