# Generated by Django 2.1.2 on 2019-08-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_merge_20190807_1646'),
        ('core', '0082_newslettersubscriber_site'),
    ]

    operations = [
    ]
