# Generated by Django 2.1.2 on 2019-08-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_auto_20190816_0917'),
        ('core', '0083_merge_20190814_1043'),
    ]

    operations = [
    ]
