# Generated by Django 2.1.2 on 2019-08-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_merge_20190816_0917'),
        ('core', '0084_auto_20190821_1518'),
    ]

    operations = [
    ]
