# Generated by Django 2.2.2 on 2019-08-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20190823_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataviz',
            options={'ordering': ['date']},
        ),
    ]
