# Generated by Django 2.1.2 on 2019-08-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20190823_1434'),
        ('core', '0085_merge_20190821_1535'),
    ]

    operations = [
    ]
