# Generated by Django 2.1.2 on 2019-08-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20190828_0548'),
        ('core', '0086_merge_20190823_1536'),
    ]

    operations = [
    ]
