# Generated by Django 2.1.2 on 2019-09-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_merge_20190828_0548'),
        ('core', '0087_auto_20190917_0625'),
    ]

    operations = [
    ]
