# Generated by Django 2.1.2 on 2019-09-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_merge_20190917_0625'),
        ('core', '0088_auto_20190930_1520'),
    ]

    operations = [
    ]
