# Generated by Django 2.1.2 on 2019-10-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_merge_20190930_1519'),
        ('core', '0089_auto_20191003_1836'),
    ]

    operations = [
    ]
