# Generated by Django 2.2.2 on 2019-10-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_methodclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substances', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Selected specific substances (elements and basic compounds only)', max_length=1, null=True)),
                ('materials', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Materials / bulk materials', max_length=1, null=True)),
                ('energy', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Energy', max_length=1, null=True)),
                ('outputs', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Outputs to environment', max_length=1, null=True)),
                ('recycling', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Recyling of material and energy', max_length=1, null=True)),
                ('stock_changes', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Stock changes', max_length=1, null=True)),
                ('specific', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Specific goods and services', max_length=1, null=True)),
                ('production', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Production processes', max_length=1, null=True)),
                ('between_flows', models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Specification of flows between sectors, industries or acticity fields, or other system components', max_length=1, null=True)),
                ('entity', models.TextField(blank=True, help_text='Key socio-institutional entity (driving force boundary for induced flows)', null=True)),
                ('classification', models.ManyToManyField(blank=True, to='core.MethodClassification')),
                ('scale', models.ManyToManyField(blank=True, to='core.MethodScale')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Tag')),
            ],
        ),
    ]
