# Generated by Django 2.1.2 on 2019-10-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20191022_1548'),
        ('core', '0090_merge_20191003_1836'),
    ]

    operations = [
    ]
