# Generated by Django 2.2.2 on 2019-10-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiplicity', '0050_auto_20190701_0635'),
        ('core', '0092_auto_20191022_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ongoing', models.CharField(blank=True, help_text='Do they continue to implement it?', max_length=255, null=True)),
                ('consideration', models.TextField(blank=True, help_text='Circular economy / closing loop consideration', null=True)),
                ('target_audience', models.TextField(blank=True, help_text='Target audience of results', null=True)),
                ('indicators', models.TextField(blank=True, help_text='Indicators', null=True)),
                ('pros', models.TextField(blank=True, help_text='Indicators', null=True)),
                ('cons', models.TextField(blank=True, help_text='Indicators', null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose of the study', null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Method')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reference')),
                ('spaces', models.ManyToManyField(blank=True, to='multiplicity.ReferenceSpace')),
            ],
        ),
    ]
