# Generated by Django 2.2.2 on 2019-10-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_casestudy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='method',
            field=models.OneToOneField(limit_choices_to={'parent_tag__id': 318}, on_delete=django.db.models.deletion.CASCADE, to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='reference',
            field=models.ForeignKey(limit_choices_to={'type__id': 3}, on_delete=django.db.models.deletion.CASCADE, to='core.Reference'),
        ),
    ]
