# Generated by Django 2.2.2 on 2019-10-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_auto_20191022_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reference'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='spaces',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type__id': 3}, to='multiplicity.ReferenceSpace'),
        ),
    ]
