# Generated by Django 2.1.2 on 2019-10-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20191022_1602'),
        ('core', '0093_merge_20191022_1549'),
    ]

    operations = [
    ]
