# Generated by Django 2.2.2 on 2019-10-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20191023_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='substances',
            field=models.CharField(blank=True, choices=[(3, '3 - The item is a defining feature of the approach'), (2, '2 - The feature is typically included in the techique'), (1, '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way')], help_text='Elements and basic compounds only', max_length=2, null=True, verbose_name='selected specific substances'),
        ),
    ]
