# Generated by Django 2.2.2 on 2019-10-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20191023_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodTemporalBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='avoidance_double_counting',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='cradle_to_grave',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], help_text='Note: could also be considered as consumption-based accounting?)', max_length=1, null=True, verbose_name='cradle-to-grave sources of flows'),
        ),
        migrations.AddField(
            model_name='method',
            name='hidden_flows',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='accounts for hidden flows'),
        ),
        migrations.AddField(
            model_name='method',
            name='impacts',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='quantitative weighting of impacts of material flows'),
        ),
        migrations.AddField(
            model_name='method',
            name='main_measurement_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='mass_balancing',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='sustainability_criteria_reference',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='between_flows',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], help_text='Specification of flows between sectors, industries or acticity fields, or other system components', max_length=1, null=True, verbose_name='between-flows'),
        ),
        migrations.AlterField(
            model_name='method',
            name='energy',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='materials',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='materials / bulk materials'),
        ),
        migrations.AlterField(
            model_name='method',
            name='outputs',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='outputs to environment'),
        ),
        migrations.AlterField(
            model_name='method',
            name='production',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='production processes'),
        ),
        migrations.AlterField(
            model_name='method',
            name='recycling',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='recyling of material and energy'),
        ),
        migrations.AlterField(
            model_name='method',
            name='specific',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='specific goods and services'),
        ),
        migrations.AlterField(
            model_name='method',
            name='stock_changes',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], max_length=1, null=True, verbose_name='stock changes'),
        ),
        migrations.AlterField(
            model_name='method',
            name='substances',
            field=models.CharField(blank=True, choices=[('3', '3 - The item is a defining feature of the approach'), ('2', '2 - The feature is typically included in the techique'), ('1', '1 - The item is included only occasionally in the mode of analysis, and in a partial or conditional way'), ('0', '0 - Not included at all')], help_text='Elements and basic compounds only', max_length=1, null=True, verbose_name='selected specific substances'),
        ),
        migrations.AddField(
            model_name='method',
            name='temporal_study_boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MethodTemporalBoundary'),
        ),
    ]
