# Generated by Django 2.1.2 on 2019-10-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20191023_1454'),
        ('core', '0096_merge_20191022_1612'),
    ]

    operations = [
    ]
