# Generated by Django 2.2.2 on 2019-10-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20191023_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='scale',
        ),
        migrations.DeleteModel(
            name='MethodScale',
        ),
    ]
