# Generated by Django 2.2.2 on 2019-10-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_auto_20191024_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='scale',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent_tag__id': 320}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='method_scales', to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='method',
            name='tag',
            field=models.OneToOneField(limit_choices_to={'parent_tag__id': 318}, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='core.Tag'),
        ),
    ]
