# Generated by Django 2.2.2 on 2019-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20191024_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='scale',
        ),
        migrations.AddField(
            model_name='method',
            name='scale',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent_tag__id': 320}, related_name='method_scales', to='core.Tag'),
        ),
    ]
