# Generated by Django 2.1.2 on 2019-10-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_tag_include_in_glossary'),
        ('core', '0100_merge_20191023_1454'),
    ]

    operations = [
    ]
