# Generated by Django 2.1.2 on 2019-10-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20191024_0711'),
        ('core', '0104_merge_20191024_0646'),
    ]

    operations = [
    ]
