# Generated by Django 2.2.2 on 2019-10-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_method_internal_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['tag__name']},
        ),
    ]
