# Generated by Django 2.1.2 on 2019-10-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_method_internal_notes'),
        ('core', '0105_merge_20191024_0710'),
    ]

    operations = [
    ]
