# Generated by Django 2.1.2 on 2019-10-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20191024_0738'),
        ('core', '0106_merge_20191024_0726'),
    ]

    operations = [
    ]
