# Generated by Django 2.2.2 on 2019-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20191024_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='avoidance_double_counting',
        ),
        migrations.AddField(
            model_name='method',
            name='also_known_as',
            field=models.TextField(blank=True, null=True),
        ),
    ]
