# Generated by Django 2.2.2 on 2019-10-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20191024_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='avoidance_double_counting',
            field=models.NullBooleanField(),
        ),
    ]
