# Generated by Django 2.1.2 on 2019-10-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_method_avoidance_double_counting'),
        ('core', '0107_merge_20191024_0737'),
    ]

    operations = [
    ]
