# Generated by Django 2.2.2 on 2019-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_method_avoidance_double_counting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='developed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='material_groups',
            field=models.ManyToManyField(blank=True, to='core.MaterialGroup'),
        ),
        migrations.AddField(
            model_name='project',
            name='material_groups',
            field=models.ManyToManyField(blank=True, to='core.MaterialGroup'),
        ),
    ]
