# Generated by Django 2.2.2 on 2019-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20191029_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['tag__name'], 'verbose_name': 'methodology', 'verbose_name_plural': 'methodologies'},
        ),
        migrations.AddField(
            model_name='method',
            name='based_on',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='gaps_addressed',
            field=models.TextField(blank=True, help_text='What gaps does in other methodologies does this particular methodology address?', null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='materials_catalog_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='next_steps',
            field=models.TextField(blank=True, help_text='The proposed next steps to further develop/improve this methodology', null=True),
        ),
    ]
