# Generated by Django 2.1.2 on 2019-10-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20191029_1729'),
        ('core', '0109_merge_20191024_1906'),
    ]

    operations = [
    ]
