# Generated by Django 2.1.2 on 2019-11-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_merge_20191029_1728'),
        ('core', '0110_auto_20191109_1454'),
    ]

    operations = [
    ]
