# Generated by Django 2.2.2 on 2019-11-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20191112_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='output_articles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='output_reports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='output_tools',
            field=models.TextField(blank=True, null=True),
        ),
    ]
