# Generated by Django 2.2.2 on 2019-11-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20191124_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
