# Generated by Django 2.2.2 on 2019-11-24 09:19

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_project_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='project',
            name='methodologies_tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent_tag__id': 318}, to='core.Tag'),
        ),
    ]
