# Generated by Django 2.2.7 on 2019-11-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_reference_cityloops'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='cityloops_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
