# Generated by Django 2.2.7 on 2019-11-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_reference_cityloops_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='cityloops_comments_import',
            field=models.TextField(blank=True, help_text='Additional comments about the importing process', null=True),
        ),
    ]
