# Generated by Django 2.2.7 on 2019-12-04 17:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_reference_cityloops_comments_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='method',
            name='method_class',
            field=models.CharField(blank=True, choices=[('3', 'Relation in UM systems'), ('2', 'Flows of substances'), ('1', 'Environmental impacts')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MethodCategory'),
        ),
    ]
