# Generated by Django 2.2.7 on 2019-12-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20191204_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='include_in_list',
            field=models.NullBooleanField(default=False),
        ),
    ]
