# Generated by Django 2.2.7 on 2019-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_method_include_in_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='print_aim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='print_relevance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='relevance',
            field=models.CharField(blank=True, choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1, null=True),
        ),
    ]
