# Generated by Django 2.2.7 on 2019-12-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_auto_20191208_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
