# Generated by Django 2.2.7 on 2019-12-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_auto_20191220_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_accounting_method',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='relevance',
            field=models.CharField(blank=True, choices=[('u', 'Unknown'), ('l', 'Low'), ('m', 'Medium'), ('h', 'High')], max_length=1, null=True),
        ),
    ]
