# Generated by Django 2.2.7 on 2019-12-22 15:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20191221_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['tag__name']},
        ),
        migrations.AddField(
            model_name='method',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'Not worked on'), (2, 'In progress'), (3, 'Draft ready for review'), (4, 'Reviewed - DONE'), (5, 'External copy')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='strengths',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='strengths'),
        ),
        migrations.AddField(
            model_name='method',
            name='weaknesses',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='weaknesses'),
        ),
    ]
