# Generated by Django 2.2.7 on 2019-12-22 15:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_auto_20191222_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='method',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='description'),
        ),
    ]
