# Generated by Django 2.2.7 on 2019-12-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_auto_20191222_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='status',
            field=models.CharField(blank=True, choices=[('nw', 'Not worked on'), ('ip', 'In progress'), ('dr', 'Draft ready for review'), ('rv', 'Reviewed - DONE'), ('ec', 'External copy'), ('sk', 'Skip - will not be published')], max_length=2, null=True),
        ),
    ]
