# Generated by Django 2.2.7 on 2019-12-23 20:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_auto_20191222_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodclassification',
            options={'verbose_name': 'method family', 'verbose_name_plural': 'Method families'},
        ),
        migrations.AddField(
            model_name='methodclassification',
            name='strengths',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='strengths'),
        ),
        migrations.AddField(
            model_name='methodclassification',
            name='weaknesses',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='weaknesses'),
        ),
    ]
