# Generated by Django 2.2.7 on 2019-12-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20191223_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['position', 'tag__name']},
        ),
        migrations.AddField(
            model_name='method',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
